### ISSUE TITLE
Unable to view a pen in IE9

### ISSUE THREAD

**Issue by simonsmith** [CodePen/CodePen-Bug-Reporting-Only#103]
Hey,

Whilst I understand that supporting old browsers is a pain, could there not be a link to allow me to carry on to the pen in IE9? I often need to test a JS or CSS demo in multiple browsers and this door slam makes it tricky.

**Comment by chriscoyier** [comment]
Full Page View = http://blog.codepen.io/documentation/views/full-page-view/

Debug View = http://blog.codepen.io/documentation/views/debug-view/

Livew View = http://blog.codepen.io/documentation/pro-features/live-view/

All should work in IE 9. It's true that navigating the normal way through the site in IE 9 is probably going to be a pain to even get to those views, so ideally we do something better there to help. But for now, the recommended way is to just copy the link from the browser you actually work in and paste it (or otherwise send it) to the browser you want to test in.

**Comment by simonsmith** [comment]
Full Page view will do the trick. Thanks
