### ISSUE TITLE
TypeScript compiler doesn't emit decorator metadata

### ISSUE THREAD

**Issue by pe8ter** [CodePen/CodePen-Bug-Reporting-Only#117]
CodePen's TypeScript compiler does not have the `"emitDecoratorMetadata": true` property set which makes it difficult to use Angular 2 for more than the most basic examples. [This Pen](http://codepen.io/pe8ter/pen/rxXGXZ) should but does not work because the compiled constructor lacks the necessary metadata to get the requested parameter (line 15):

```typescript
constructor(private _cd: ChangeDetectorRef) {}
```

It would be great to have that flag on, or at least have the option to have that flag on.

Thanks!

**Comment by chriscoyier** [comment]
Looks like it compiles still, so that's good.

We might be able to set this flag, but we're often hesitant to do stuff like that. Mostly out of fear. We don't actually know that much about TypeScript, and on purpose don't offer ways to customize it on a per-Pen basis, so any change we make to it affects all present, past, and future Pens using it. 

Do you think this is the kind of flag you set that has zero impact other than more support?

**Comment by pe8ter** [comment]
Theoretically, enabling the `emitDecoratorMetadata` flag _could_ impact existing Pens. If someone were to call the Reflect API for their class explicitly and happened to use one of the three metadata keys emitted by the TypeScript compiler (`design:type`,` design:paramtypes`, or `design:returntype`) for reasons other than filling in the missing output of the compiler then that pen could break.

Likely? No.

Possible? Sure.

BTW, here's a [pen](http://codepen.io/pe8ter/pen/dMbWJg) showing how to write the missing emitted metadata boilerplate. It must be maintained manually which is tedious and prone to errors, but does fix the pen from the first comment.

**Comment by chriscoyier** [comment]
I'm gonna tag this as `TypeScript` and close it for now. 

It likely makes more sense for us to tackle this as part of a more focused effort on improving TypeScript as a whole, if we can.
