### ISSUE TITLE
Double clicking the 'clear' button on the console expands/collapses the drawer

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#137]
Looks like clicks on buttons propagate to the drawer's handle.

![tfyppvubc1](https://cloud.githubusercontent.com/assets/8040471/13514831/1ac3a1f6-e161-11e5-894c-c3c5ce18579f.gif)

**Comment by chriscoyier** [comment]
Good catch!

Under normal circumstances stopping propagation of the `dblclick` event on that button I think would stop this action. But, turns out this double click action is a specially concocted thing that's built into the custom dragging stuff @desandro built that deals with events a bit differnently.

While I'd call this behavior a *little* weird, I think we'll just let it be as it's not really causing any harm. The console still clears. The X button still closes the console.
