### ISSUE TITLE
$("anyElementId").css("visibility" "visible"); not working in full page view

### ISSUE THREAD

**Issue by KoushikKumar** [CodePen/CodePen-Bug-Reporting-Only#138]
Demo:: http://codepen.io/KoushikKumar/full/mPezXM/

This works in editors view but not in full page view

**Comment by chriscoyier** [comment]
The trouble here is that there is a real syntax error. It shouldn't be working in Editor View (missing comma), but we're fixing it for you. We shouldn't be doing that, and showing an error instead. We'll get that fixed as soon as we can.

**Comment by chriscoyier** [comment]
Fixed.

You'll see this now in the editor, as you should because it's a real error:

![screen shot 2016-03-08 at 7 41 12 am](https://cloud.githubusercontent.com/assets/69156/13603218/330f8042-e501-11e5-912a-748316348809.png)

And in full you'll see the error in the console:

![screen shot 2016-03-08 at 7 42 06 am](https://cloud.githubusercontent.com/assets/69156/13603232/4b464f7e-e501-11e5-9df8-040040e89adf.png)
