### ISSUE TITLE
Fixed position property ignored in iOS

### ISSUE THREAD

**Issue by hexagoncircle** [CodePen/CodePen-Bug-Reporting-Only#139]
It seems like `position:fixed` is ignored when viewing a pen on a mobile device (specifically the device I have listed below, I have yet to test others). I've examined a few pens that use position:fixed and it seems like it happens with them as well.

I'm viewing the following codepen example on an iPhone 6s: http://codepen.io/hexagoncircle/pen/yOYGjp
Same code works as expected here: http://hexagoncircle.com/fb/

Issue appears in both Safari and Chrome browsers, iOS version 9.2.1.

**Comment by chriscoyier** [comment]
This is a weird one, but known. It's not that position fixed doesn't work, it's that the iframe containing the demo is as tall as the content it contains. I appears to scroll, because we wrap it in a parent DIV that scrolls. But since the iframe that shows the demo itself doesn't scroll, you don't see fixed positioning doing anything. 

I think it's an iOS bug, but I'm not super sure they consider it a bug, it's been that way a long time. We'll have to do another round of testing on it soon to see if it's either fixed or we can work around it another way.

**Comment by hexagoncircle** [comment]
Gotcha, thanks for the answer. If I come across any solutions I'll be sure to post it here.
