### ISSUE TITLE
Prevent browser crashing in search results

### ISSUE THREAD

**Issue by dangodev** [CodePen/CodePen-Bug-Reporting-Only#151]
Is there some way to **flag** certain pens as “crashy” and prevent thumbnail rendering so that search isn’t inhibited?

Take for instance: http://codepen.io/Ananze/pen/yyNqZW. It comes up when I [run a search for `contour`](http://codepen.io/search/pens?q=contour&limit=all&order=popularity&depth=everything&show_forks=false), and crashes the page before I can even hit “next page” in the results to find pens I’m actually looking for.

I understand that the pen itself doesn’t run in Chrome. That’s fine; nothing you can do about that. That’s the responsibility of the creator. But I want to still be able to use CodePen if this comes up by some coincidence in search.

Suggestion: can certain pens be flagged so that they don’t try and render in search results? Maybe with a static thumbnail image with an explanation: `This pen’s rendering has been disabled in thumbnail view; click to expand`, etc.

**Comment by rachsmithcodes** [comment]
That solution would be ideal. Unfortunately, for us to be able to determine which pens are going to crash via some sort of code analysis is not really feasible at the moment. The "aww snap" is caused by memory usage more often than not and can be effected by other things like how many Chrome tabs you have open etc. Even a user flagging system would be difficult to get right because some pens on one machine may crash but could be totally fine on other machines/devices/browsers. 

One thing you can do to prevent the "aww snap" is turn your user browsing settings to images instead of iframes while searching. This will turn all pens previews in search to images which is not 100% ideal I know but it will stop the browser crashes.

The Chrome crashing thing is something I would love to find a solution to though so I've put your flagging suggestion in our internal issue for this problem. Thanks!

**Comment by dangodev** [comment]
Did not know about the images setting; that’s really helpful. Thanks!
