### ISSUE TITLE
The page with fullpage.js becomes really messy on iOS

### ISSUE THREAD

**Issue by zubko** [CodePen/CodePen-Bug-Reporting-Only#157]
By itself [fullpage.js](https://github.com/alvarotrigo/fullPage.js/) supports iPhones. I think it interferes with some CodePen framing code.

Esp when pen is in Full Page view. In Debug view on iPhone it works fine.
Check out this pen for example: http://codepen.io/joe-watkins/full/rFzcf/ 
On desktop it works good. But in Full Page view in Safari of iPad iOS9 when I press navigation buttons the scrolling goes goes far away and misses the content. 

It's not mine pen, but I can make some simple pen if needed.
Or let me know pls if you think that this one should better be reported at CodePen.

**Comment by zubko** [comment]
I also noticed that when I restart the browser and it loads the page initially from Full Page view it works pretty good. But even when I "switch" from Full Page to Full Page when the loading will finish the page will be broken.

**Comment by chriscoyier** [comment]
Hey @zubko - sorry this took so long for me to respond to. 

The problem is that, in Full Page View and the (mobile) Editor View, specifically in iOS, the `<iframe>` that displays the preview is *as tall as your content is*. I think it's a bug. We can't set a height on that iframe, it just ignores it. So, we have to put it into a parent container and *that container* scrolls. 

So all that stuff that fullpage.js (I'm assuming) does is based on incorrect numbers based on an akwardly-unexpectedly tall viewport.

Graphic:

<img width="994" alt="screen shot 2016-04-14 at 11 41 29 am" src="https://cloud.githubusercontent.com/assets/69156/14538281/020b2fa4-0249-11e6-9b37-adf274930562.png">

If iOS let's us start setting heights on iframes, it'll get better.

**Comment by tomByrer** [comment]
Is there a way there could be a Full-full page view?  For example, this won't work in iPhone
http://codepen.io/tomByrer/full/QNZLvQ/
but this does
https://tombyrer.github.io/demo-sticky-nav-hero/
https://github.com/tomByrer/demo-sticky-nav-hero/tree/gh-pages

**Comment by mariemosley** [comment]
@tomByrer you can use your Pen's Debug view to see it outside of the iframe. We have more info on how Debug works in our documentation at: https://blog.codepen.io/documentation/views/debug-view/

**Comment by tomByrer** [comment]
Thanks @mariemosley; I didn't think about logging in CP on my phone...
