### ISSUE TITLE
Ideas for more Syntax Highlighting themes.

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#17]
I'm breaking a rule here: **normally this issue tracker is only for bugs**. But I'd like for there to (temporarily) be an open thread for ideas for new syntax highlighting themes to add. We only offer 5 right now and I think it makes sense to go up to 10 or 12, as long as they are really nice and well done.

Now accepting ideas.

**Comment by chriscoyier** [comment]
Easy choices: [CodeMirror supported themes](http://codemirror.net/demo/theme.html)

**Comment by chriscoyier** [comment]
Request: https://twitter.com/user/status/668483496730451969

**Comment by 223SK** [comment]
[xq-light](http://codemirror.net/demo/theme.html#xq-light) from CodeMirror looks like a nice option for light backgrounds. I have a peculiar need, which is projecting code to young students in a well-lit classroom, where dark backgrounds are hard to read. Thanks!

**Comment by chriscoyier** [comment]
After adding more... visit every one and make sure things look nice. Solarized Light is a little neglected ATM

<img width="283" alt="screen shot 2015-11-01 at 8 23 18 am" src="https://cloud.githubusercontent.com/assets/69156/10941529/7751881e-82d1-11e5-9d34-89377f91c696.png">

**Comment by bhaveshgohel** [comment]
I would love to see "cobalt2" theme by @wesbos  : https://github.com/wesbos/cobalt2  :+1:

**Comment by wesbos** [comment]
I'm happy to help make this happen

**Comment by chriscoyier** [comment]
https://github.com/YabataDesign/afterglow-theme

**Comment by bartveneman** [comment]
Ooh, I'm totally loving the DuoTone darkSpace theme in Atom, as also featured on Jan 1st on CSS-Tricks: http://simurai.com/projects/2016/01/01/duotone-themes/

**Comment by Siyanda** [comment]
Cobalt2 😀😎

**Comment by charlespeters** [comment]
oceanic next is an awesome one. https://github.com/mhartington/oceanic-next

**Comment by atelierbram** [comment]
Like @bartveneman , I would also like to see some of the DuoTone themes by Simurai included there. Have been porting them over with base16-builder to Vim, Sublime Text, and [Prism](http://localhost/~bram/syntax-highlighting/duotones/demo/dark/), but haven't started with the Codemirror template yet. Will need to find the time to do this and/or put this higher up in my "virtual" TODO-list priorities.

**Comment by npsantini** [comment]
Like @bartveneman & @atelierbram I too would like to see DuoTone themes and maybe Zenburn.

**Comment by atelierbram** [comment]
Converting DuoTone themes - to be as close to the originals as possible - to CodeMirror. Made [a few demos](http://atelierbram.github.io/syntax-highlighting/duotones/CodeMirror/demo/theme-htmlmixed.html#duotone-dark-dark).
See also [the css-files](https://github.com/atelierbram/syntax-highlighting/tree/master/duotones/output/codemirror)

**Comment by chriscoyier** [comment]
@atelierbram hot. will get some of these in there soon.

**Comment by atelierbram** [comment]
@chriscoyier Cool! 
Please let me know if there are things I can help with and/or improve upon.

**Comment by chriscoyier** [comment]
@bhaveshgohel @Siyanda @wesbos 

I got a little flow for adding new themes. Happy to add Cobalt2, but needs to be CodeMirror ready. The format is like this: https://raw.githubusercontent.com/atelierbram/syntax-highlighting/master/duotones/output/codemirror/duotone-dark-cm.css

---

Also: Oceanic, DuoTone Dark, xq-light, and a few more all definitely coming.

**Comment by chriscoyier** [comment]
On route to production!

**Comment by bensk** [comment]
Yay!

**Comment by bhaveshgohel** [comment]
@chriscoyier :+1:

**Comment by atelierbram** [comment]
@chriscoyier DuoTone Dark looks great in Codepen! Proud to see evidence of my effort in there as well, but you are too fast for me, so I'm a bit embarrassed to see a few mistakes from me in there as well. They are minor issues though:

For the HTML-view, in order to let the `.cm-bracket` prevail over `cm-tag` (_for those toned down brackets_, because of multiple classes on those brackets in the HTML on those brackets) in the cascade, it will be enough to declare the declaration-block with `.cm-bracket` _after_ the one with `.cm-tag`. See also [duotone-dark-cm.css](https://github.com/atelierbram/syntax-highlighting/blob/master/duotones/output/codemirror/duotone-dark-cm.css)

Somehow Codepen has a different (custom?) implementation of the blinking cursor, or I am missing something, but anyway, in my test setup I couldn't replicate the implementation of the cursor how it was on Codepen. So I copied over the styling of the Codepen `CSS` but lacking visual feedback sure enough gave it wrong (border-)values for background.

So it should be:

```css
.cm-fat-cursor .CodeMirror-cursor {
  background: rgba(255,168,82,0.5);
}
```

**Comment by chriscoyier** [comment]
@atelierbram ah yes, good tweaks, going to prod today.
