### ISSUE TITLE
pens on codepen/tv have issues

### ISSUE THREAD

**Issue by pixelass** [CodePen/CodePen-Bug-Reporting-Only#171]
Some pens render differently on codepen.io/tv

I noticed this when viewing this collection: http://codepen.io/collection/XPYrrW/ as http://codepen.io/tv/XPYrrW

examples: 

* http://s.codepen.io/pixelass/pen/uqbjr
* http://codepen.io/pixelass/pen/clnue

I guess it is due to the `safe=true` parameter in the url. Sadly I can't access the pens outside codepen tv so I can't further investigate.

If not a bug please consider it as a question which features get disabled.

**Comment by chriscoyier** [comment]
/tv/ should generally be more permissive than any "grid" view. 

The `safe` URL param is essentially allowing animations to run forever rather than stopping at a few seconds. Is that the main difference you are seeing? 

If not, screenshots would be useful (I can re-open if there is a bug beyond that).

**Comment by pixelass** [comment]
Here is a comparison. It seems like filters are not applied 

<img width="876" alt="screen shot 2016-03-29 at 9 47 50 pm" src="https://cloud.githubusercontent.com/assets/1148334/14121474/f3584274-f5f7-11e5-80fd-c1e44aa13099.png">
<img width="678" alt="screen shot 2016-03-29 at 9 46 41 pm" src="https://cloud.githubusercontent.com/assets/1148334/14121473/f3545772-f5f7-11e5-9c23-9503d2ba18c2.png">
