### ISSUE TITLE
Getting javascript error in full mode with a for loop that omits blocks

### ISSUE THREAD

**Issue by tchaffee** [CodePen/CodePen-Bug-Reporting-Only#176]
If you use a for loop that omits the three blocks, like this:

```
for ( ; ; ) {
.... more code here.
}
```

You'll get an error saying "Unexpected token {" when viewing the codepen in full page mode.

Here's an example pen that gets the error:

http://codepen.io/tchaffee/full/BKwjBe/

**Comment by Haktrum** [comment]
The parenthesis get deleted somehow.
From the source:
```HTML
        <script>
      var i = 0;
for  {
    if (window.CP.shouldStopExecution(1)) {
        break;
    }
    if (i === 0) {
        break;
    }
}
window.CP.exitedLoop(1);
      //@ sourceURL=pen.js
    </script>
```

**Comment by rachsmithcodes** [comment]
It seems the statement is causing problems for our "infinite loop" detection code that we have in place to prevent the browser getting locked up by JavaScript.

Since `for ( ; ; ) { }` doesn't actually execute anything in JavaScript its not really a priority to make this statement work with the infinite loop detection. May I suggest using a while loop to achieve what it looks like you're trying to do in the pen above eg.

```
while (i !== 0) {

}
```

**Comment by tchaffee** [comment]
Rather than closing this, how about at least a warning message that makes sense? It took me quite a while to debug this and figure out that Codepen was changing my code into non-valid javascript.
