### ISSUE TITLE
Weird Prefilling of Onboarding Step

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#181]
I was signing up a new free user (my brother's wife) to help her post a job, and the onboarding step for her was prefilled with my profiles stuff:

![screen shot 2016-04-03 at 10 41 51 am](https://cloud.githubusercontent.com/assets/69156/14236257/5a8a78d6-f9c7-11e5-8352-455e90a8690a.png)

**Comment by rachsmithcodes** [comment]
So this is because of a couple of things:
We store that form data in local storage for the scenario where you navigate away from the page (to auth Twitter/Github) and we don't want it to wipe out the filling you've done it. We then clear the local storage when you hit submit.
In the scenario that people (accidentally) end up at that page after you've already done onboarding, we prefill with your existing user profile data so you don't accidentally overwrite it all with blanks.

So to create above you need to:
- go to signup/profile as an existing user
- navigate away from the page/close tab (don't hit submit)
- sign up on your computer as someone else

**Comment by rachsmithcodes** [comment]
and now after I've typed all that out I've realised how we can fix it 😆
