### ISSUE TITLE
HTTPS problem

### ISSUE THREAD

**Issue by TimPietrusky** [CodePen/CodePen-Bug-Reporting-Only#19]
The following URL's are blocked in Chrome 46 if a pen is served via HTTPS:

<pre>
http://codepen.io/&lt;user>/detailstab/&lt;penid>?type=lovers&page=1
http://codepen.io/love/pen/&lt;penid>/1
http://codepen.io/&lt;user>/detailstab/&lt;penid>?type=forks&page=1
</pre>

## Error

(Chrome console)

<pre>
Mixed Content: The page at '&lt;HTTPS URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '&lt;HTTP URL>'. This request has been blocked; the content must be served over HTTPS.
</pre>

## Effect

Because of this it's not possible to heart a pen or see the lovers / forks of a pen. 

## Example

Switch from HTTP to HTTPS using a pen of your choice.

**Comment by tsabat** [comment]
@chriscoyier we should fix the google-analytics issue here:

http://d.pr/i/Xtm2/1d5veyQW

But, @TimPietrusky we don't really support https as a use-case yet.  It'd be nice to switch over to it someday, but I'll have to be a thoughtful transition.  For example,  due to asset loading, old pens will probably always have to serve on http unless the user explicitly converts it.  While new pens will serve by default on https, but with the option to serve insecure.

**Comment by chriscoyier** [comment]
@tsabat it's super weird that the errors shows for google analytics... what it's actually complaining about is a link to an image file. I kinda don't wanna fix it for the same reason you don't wanna piecemeal fix HTTPS routes. I could hardcode that image to load via HTTPS, but then we're not using the asset pipeline asset-url() function that supposed to handle that for us, and push us further away from getting on a CDN.  

@TimPietrusky Totally legit that you should expect to be able to heart a Pen from a Pen loaded over HTTPS. In talking to @tsabat about it - he just doesn't want to fix a route here, fix a route there and poke away at it, he'd rather make it a concentrated effort to fix all of HTTPS on CodePen. 

It's a bit hard, because we can't force HTTPS on a lot of pages. If we did, any page that has a Pen on it in any fashion that links to a non-secure JavaScript file would be broken (not just mixed content warning). We don't want to force HTTP either, because if you really want to load the page via HTTPS you should be able to. 

Our best idea at the moment is to start forcing HTTPS for NEW stuff (and show stern warnings when you're able to link something up that isn't secure), and grandfather old stuff into the either/or system.

**Comment by chriscoyier** [comment]
Gonna move this to a master issue on HTTPS
