### ISSUE TITLE
Typing out a for loop will hang

### ISSUE THREAD

**Issue by idank** [CodePen/CodePen-Bug-Reporting-Only#194]
It seems like the infinite loop detector doesn't catch a for-loop as it gets written, e.g. start with

`for (`

editor completes to

`for ()`

add parts of the for

`for (var i = 0; i < something;)`

at this point if auto refresh kicks in, the pen is stuck because `i` never increments, furthermore auto save means the pen is now in an unrecoverable state.

**Comment by alexzaworski** [comment]
Hey just a heads up you can [visit your pen using the url parameter `?turn_off_js=true`](https://blog.codepen.io/documentation/features/turn-off-javascript-in-previews/) if you run into this sort of thing which can help you get your work back.

**Comment by pixelass** [comment]
@idank auto-compile will always cause an issue. I suggest turning it off when working with keyframe animations, javaScript recursions/iterations or when loading lots of libraries.

I always open and save as private to make sure autosave kicks in. I have lost a lot of awesome things due to crashes and unsaved states. IMHO this is the only reason why autosave makes sense at all (my most hated & most valued feature at the same time).

I suggested being able to change the debounce for compiling (e.g. 500ms, 1000ms...) a while ago. I am still hoping it will be added some time.

**Comment by idank** [comment]
I agree this is hard to get working with every possible code out there. But, assuming there's a mechanism that detects whether an auto compile should commence, a for loop being typed (among other things) should tell it to pause.

Having `turn_off_js=true` helps if the work was saved though, so thanks for that.

**Comment by chriscoyier** [comment]
Seems to catch for me: http://d.pr/v/18fuP/4H8WFLer

Or, be invalid syntax so it doesn't run. Another thing that should be helping is that it shouldn't try to rerun the code until you leave the line you're currently working on. Also, if you want it to try to catch infinite loops FASTER, you can adjust the variables like described here: https://github.com/CodePen/CodePen-Bug-Reporting-Only/issues/242#issuecomment-222771824
