### ISSUE TITLE
postcss-custom-media add-on is broken

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#21]
Test case: http://codepen.io/team/css-tricks/pen/76685bd96413fa47ff6a889108492766/

**Comment by soulchainer** [comment]
+1

And I suspect (but I can be wrong, of course), that it's broken for, at least, almost two months now. Because before I noticed codepen has a github account, [I warned about this via twitter](https://twitter.com/juanriqgon/status/654700131313324032). That or it's broken **again**. Because it seems a big coincidence for it to be broken everytime I decide to use it again... I'm out of luck xD.

Hope it will be sorted out eventually :).

**Comment by tsabat** [comment]
Fixed.  We somehow did not include that in our releases. Ever...
