### ISSUE TITLE
Possible Hallucination: Page on live view for mobile debugging reloads

### ISSUE THREAD

**Issue by sdras** [CodePen/CodePen-Bug-Reporting-Only#215]
Is it just me or does the page always reload on apple iphone after 3 seconds? Is this an Apple thing? Is it just my pens? Am I nuts? (separate issue)

Anyways, just trying to track down the source of this because it really messes with animations and makes them look funky when they start over all of a sudden. It also locks up the page sometimes.

Thanks,
Sarah

**Comment by chriscoyier** [comment]
This seems like a legit bug - because of how consistent it is. It seems like **right at 2 seconds in** Live View decides to refresh the preview entirely. From then on out, CSS changes are injected, but you get that initial reload after things have already kicked off once, whether anything has changed or not.

![apr-29-2016 11-32-47](https://cloud.githubusercontent.com/assets/69156/14922629/501dbb4c-0dfe-11e6-8f15-c528be2cf0f4.gif)

**Comment by tholman** [comment]
I get the impression this might have been like this from the start.

When the live view loads, it loads the pen in its last saved state, the editor and the other frame then do a little handshake, which when successful -> sends over the new pen data (any changes then load in).

We could try to squeeze something in to tell it not to update if no changes have been made to the pen... but I think this might be built as a feature to also make all live views synced as much as possible... So when a new life view is made, it also refreshes all of them.

**Comment by mariemosley** [comment]
We've moved this to our [Known Issues trello board](https://trello.com/c/ymuOdbXn/22-live-view-page-flicker-on-iphone). Thanks for taking the time to report it Sarah!
