### ISSUE TITLE
Some pages stopped working

### ISSUE THREAD

**Issue by Lemondoge** [CodePen/CodePen-Bug-Reporting-Only#223]
It seems that some pages (e.g., the [profile settings](http://codepen.io/yourusernameoncodepen/settings/profile) page) aren't working; they appear to only show the "toolbar" at the top.

Could you please fix this?

As long as it is still broken, probably no one will be able to:

1. upgrade to PRO
2. change their settings

**Comment by quezo** [comment]
The pages work on my browser and we haven't had any other reports. Can you upload a screenshot of the errors? Also any details on your browser/OS would help. Thanks!

**Comment by Lemondoge** [comment]
I've uploaded an image of the error, as appears on the "Settings - Profile" page:

![codepen glitch](https://cloud.githubusercontent.com/assets/17170154/15057679/9cb79778-12dd-11e6-9f0b-55a7451fd5a6.png)

It seems that the error only happens with [Google Chrome](https://en.wikipedia.org/wiki/Google_Chrome); I tested it with two other browsers, and neither of them encountered the error.

**Comment by mariemosley** [comment]
The most likely cause for this is a browser extension interfering with your connection to CodePen. Since you mentioned it's only happening in Chrome, I'm 99% sure that's what's happening here :) Try opening CodePen in an incognito window to test — if it works then, it's definitely an extension. The fix then would be to either disable the extension that's interfering, or make changes to its settings.

If those suggestions don't help please get in touch with us at support@codepen.io and we'll do some more troubleshooting!

**Comment by Lemondoge** [comment]
I managed to figure it out and fix it (it was an extension after all).

@mariemosley: Thank you for the suggestion.
