### ISSUE TITLE
Blog spellcheck

### ISSUE THREAD

**Issue by mariemosley** [CodePen/CodePen-Bug-Reporting-Only#234]
https://twitter.com/AmeliasBrain/status/731188167680925697

Blog spellcheck could use some tweaks to make it more code-friendly and sensible

Lets teach it to:

- Recognize CSS and other "dev" words
- Ignore numbers

**Comment by AmeliaBR** [comment]
Idea for building the custom "dev" dictionary: run a word-count scraper on all existing published pens to identify the most commonly used words that are being flagged as errors.

Will need some manual curation to weed out words that are just common spelling mistakes, but it would be a start to making this a very CodePen-focused feature.

**Comment by chriscoyier** [comment]
I started looking into this and it's harder than I thought it was going to be. Numbers are already in the dictionary, so that sucks they aren't caught. But apparently it's just 1-9 aren't caught, but like "50" is. Adding words is also tricker than I'd like, and I'd prefer not to monkey patch it. There is an open thread about allowing for customizations though, so let's leave it in those hands for a little bit: https://github.com/NextStepWebs/codemirror-spell-checker/issues/16
