### ISSUE TITLE
Link to MIT licence from all public pens

### ISSUE THREAD

**Issue by AmeliaBR** [CodePen/CodePen-Bug-Reporting-Only#236]
There seems to be [a lot of confusion and complaints](https://twitter.com/search?q=codepen%20%20(license%20OR%20licence%20OR%20MIT)&src=typd ) that stem from poor understanding of the MIT Licence, from both creators and users of pens.  A constant, subtle reminder of the licence could help clear the air.

I was certainly one of the people who did not discover the automatic MIT licence on public pens until I'd been using the site a while, and was rather annoyed about it.  And that is without having to deal with people who copy without concern for even the minor attribution requirements of MIT.

For editor and full page view, a logical place to add a link (to the [CodePen licence information page](https://blog.codepen.io/legal/licensing/)) would be after the creator's name in the header:

![Mock-up screenshot of the header for editor/full page view, with "A pen by" changed to "A pen ©", and a linked badge "MIT Licence" after the user's name](https://cloud.githubusercontent.com/assets/9876129/15269347/31ac1c82-19b9-11e6-91c3-95c400554771.png)

A similar link could be added into the details view and embeds.

Some complications to consider:

- For private pens, CodePen doesn't apply a licence, so just leave the badge off: pen is copyright the author, contact them for licencing details.
- However, if a private pen has been forked from someone else's public pen, it needs to preserve the MIT licence.
- If this is a forked pen, the copyright is actually shared between the "hosting" user and the previous creators. Maybe the credit line could add an extra link in these cases, so it is "a pen by Joe Blow + 3 others", where "+ 3 others" links to or pops up the fork history.  This would also help make forks visible and properly credited.

**Comment by chriscoyier** [comment]
Step 1 was getting it into Details View, which is live now. 
Another upcoming step is to make it more obvious during signup, which has been done but will be a little while before it's live.
Another is to get it into the editor itself, which is still being considered.

Forking is definitely a weird one. The licence itself doesn't specify anything about attribution. But it does say you should put the copyright holder name in the license and does say:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

So if you take that to include the line with the name/year in it as well, it's almost like a fork should have two copies of the license. But I doubt that's what is intended. Forking is a bit unusual on CodePen also, since it's *flat*. For example, if a fork is forked, it becomes a fork of the original pen, not of the fork. No nesting. I'm not sure it's appropriate to list other people in the license who may or may not have had anything to do with it. And on the flip side, only list two people when actually more people worked on it. For just, just leaving the Pen owner in the license.
