### ISSUE TITLE
Public/private toggle in Pen Settings modal animates out too slowly

### ISSUE THREAD

**Issue by alexzaworski** [CodePen/CodePen-Bug-Reporting-Only#246]
Here's a slowed-down gif that makes it really easy to see the issue:

![vftquwy4ox](https://cloud.githubusercontent.com/assets/8040471/15406984/a26ccc52-1dbd-11e6-8de4-a1c588ce498c.gif)

It seems to be caused by the toggle having its own transition rules. Something like this would fix it and prevent this from happening in the future:

```
.pen-settings-modal:not(.open) *,
.pen-settings-modal:not(.open) *:after,
.pen-settings-modal:not(.open) *:before {
  transition: none;
}
```

**Comment by chriscoyier** [comment]
Pretty weird one. I was trying to dig into why that particular element and no others, but didn't find anything compelling. Rather than do something heavy handed like effect all descendents, I'm just hiding/showing the toggle more explicitly and it seems fine. It'll go out whenever the next deploy is.
