### ISSUE TITLE
Backspace in editor sometimes doesn't get caught in Vivaldi

### ISSUE THREAD

**Issue by justinforce** [CodePen/CodePen-Bug-Reporting-Only#249]
Sometimes when I hit the backspace key (labeled "delete" on this keyboard) the editor fails to prevent the default action and my browser navigates away from the page and I lose work. `Command-S` also opens the browser's dialog to save the webpage. I don't know how much you guys can do about this stuff. I'm going to see if I can disable the backspace binding in Vivaldi as a quick fix. Hey! That worked.

![screenshot 2016-05-23 09 38 14](https://cloud.githubusercontent.com/assets/324632/15477564/1ba05c06-20ca-11e6-9c0e-f921e549d77e.png)

## Versions

| Thing | Version |
|---|---|
| Vivaldi | Vivaldi 1.1.453.54 (Stable channel) (64-bit)
| Mac OS X | 10.11.4 (15E65)
| Darwin | Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu- 3248.40.184~3/RELEASE_X86_64 (`uname -v`)
| Mac | MacBook Pro (Retina, 15-inch, Late 2013)

**Comment by chriscoyier** [comment]
I downloaded that browser and tested a bit. Confirmed that command-S opens the browser save dialog. Not sure what we can do there. We don't do anything fancy to do keybindings so perhaps this browser is just less cool about overriding that command. The backspace while in an editor just deletes the character, but if you aren't focused on an editor, I confirmed it does navigate back. And that you could lose work, because our standard `onbeforeunload` doesn't stop you, like it does in all other browsers I know about. 

I think we might have to pass on digging into this one. These are pretty sucky bugs, but this would be quite a rabbit hole for us to go down without knowing if it's even fixable at all. Being that this browser is specifically for "power users", I think it's best to leave the fixes customizations like you found.

**Comment by justinforce** [comment]
@chriscoyier Thanks! That makes a lot of sense. I'll point the Vivaldi devs at these bugs instead. It's a very new browser and these things come up from time to time.
