### ISSUE TITLE
Searching incorrectly shows the next button on the final page of results

### ISSUE THREAD

**Issue by stowball** [CodePen/CodePen-Bug-Reporting-Only#251]
If you [search for loading balls](http://codepen.io/search/pens/?depth=everything&limit=all&order=popularity&page=2&q=loading+balls&show_forks=false), it finds 24 results, yet page 2 still has the "next" pagination arrow. When clicked, it takes you to a "No Pens found for "loading balls"" page.

**Comment by chriscoyier** [comment]
I think *maybe* this is a situation where we remove Pens from the results *after* we run the query. Like, perhaps search returns 24 results, but some of them were created by a user that has since been deleted. And those Pens somehow maybe haven't been removed from the search index yet. @tim might know here.

**Comment by mariemosley** [comment]
We've moved this to our [Known Issues trello board](https://trello.com/c/GOd2ZfnA/3-search-results-pagination-arrow-sometimes-shows-when-there-are-no-more-pens-to-page-to). Thanks for taking the time to report it!
