### ISSUE TITLE
Autorun is unusable if autosave is disabled, due to loss of changes upon unintended infinite looping

### ISSUE THREAD

**Issue by monfera** [CodePen/CodePen-Bug-Reporting-Only#86]
![image](https://cloud.githubusercontent.com/assets/1548516/12953091/4fc05a4c-d019-11e5-8dab-64ec068a6d80.png)

I already had some code (which I could replicate with a simple line of console.log) and started typing a plain vanilla for loop. I got as far as what's on the screenshot and the ultimate result is that codepen froze (see on the bottom of the screenshot). 

What might be happening is quite trivial: by the time I had a syntactically valid for loop, but not yet the incrementing part, the system just ran with it. It means that a user needs to choose autosave or manual run, because something like this can cause loss of work if autorun is enabled and autosave isn't (which is my preference). 

I was quite surprised by this behavior because apparently the infinite loop problem has been around for quite some time; stumbling into this is very easy and I read there was work toward detecting it, but it apparently didn't work for the cleanest, most basic case.  

While it might be hard to detect infinite loops or other resource hogs, maybe the system could frequently save the files even if the user opted not to; and revisiting the same code (after closing the hung tab) should present the user with the option of either reverting to the last version the user saved, or the last non-infinite-loop version that the system kept around for this very purpose.

**Comment by chriscoyier** [comment]
It REALLY should catch that loop. We just had three people give it a shot and we all got:

<img width="454" alt="screen shot 2016-03-21 at 3 09 16 pm" src="https://cloud.githubusercontent.com/assets/69156/13930862/18abdde2-ef77-11e5-8251-d44e8744f4dc.png">

Sometimes it takes kind of a long time in order to catch it. The trouble is that the browser really gets chugging on the loop, and it even slows down our detection. 

If we make it more sensitive, it starts catching stuff that really isn't an infinite loop, which is even MORE annoying, believe it or not!

We'll work on dialing those knobs to be just right, if we can.
