### ISSUE TITLE
UI/UX if you paginate too far...

### ISSUE THREAD

**Issue by chriscoyier** [CodePen/CodePen-Bug-Reporting-Only#9]
@natewiley originally reported this here: https://github.com/CodePen/redesign/issues/299

![No pens](http://i.imgur.com/3gFaNai.png) 

What SHOULD we say? 

- Redirect the URL back to the last page where you DO have Pens? e.g. change /3433432/ to /84/
- Redirect to /1/
- 404?
- Show UI that says something that makes more sense like... "No Pens Found" or "You Dang Paginated too Far I Reckon."

**Comment by jakealbaugh** [comment]
The easiest fix here would be a unique message since the controller is fairly agnostic to the pen/item count. If we _really_ want a redirect, we can make it happen, but i dont think thats necessary because this should be happening accidentally. It really only happens when magicians like @natewiley scrape around trying to find the last page.

something like `if there arent any items and page number isnt 1`

**Comment by jakealbaugh** [comment]
fixed
