### ISSUE TITLE
Viewing pens in editor mode the preview pane just says, "Loading..."

### ISSUE THREAD

**Issue by jonathanbell** [CodePen/CodePen-Bug-Reporting-Only#91]
Whenever I view any of my pens in editor mode the preview pane just says "Loading.........". This issue has persisted for a while now (maybe 3 months). Viewing the pen in another view (such as "details" or "full page" does not have this issue and the pen(s) work as expected. 

The console in Chrome has this error: POST http://codepen.io/boomerang net::ERR_CONNECTION_RESET Inspecting the error the console takes me to the minified file http://assets.codepen.io/assets/common/everypage-2af946b5cfa5a5690c8b70d2c9df6e33.js

**Comment by chriscoyier** [comment]
Not quite sure on that one. We know that 1) it has persisted for you for a long time 2) it's not a widespread issue. So that leads me to think it's a consistent issue on your end - like a firewall blocking an asset or a connection? I'd look into that, as well as trying other browsers and trying incognito modes to see if it's an extension interfering.

**Comment by jonathanbell** [comment]
Nail on the head, Chris! Thank you for the help. It's only at my work... Which leads me to believe I'll have to ask them about our firewall. Thank you.
