### ISSUE TITLE
Unable to login with GitHub(Unknown GitHub User). Try again or contact support@coden.io.

### ISSUE THREAD

**Issue by mehulshyani** [CodePen/CodePen-Bug-Reporting-Only#94]
When I tried to login to codepen.io first time with my GitHub account it took me to GitHub page to authorize codepen.
Once i authorized Codepen it showed me below message in RED box 
Unable to login with GitHub(Unknown GitHub User). Try again or contact support@coden.io.

and it keeps showing the same message. I am logged into GitHub and in GitHub it shows that codepen is authorized to use account still i keep getting same message.

**Comment by chriscoyier** [comment]
You'll be able to do that when your CodePen and GitHub accounts are linked. It looks like they are not right now. Not sure why, especially since GitHub shows CodePen as an authorized app, but hey stuff happens. Here's the steps:

1. [Log into CodePen](https://codepen.io/login) using a username (or email) and password. If you don't know your password, you can [reset it](https://codepen.io/login#forgot-password). If you don't have a CodePen account at all yet, [sign up](https://codepen.io/signup/).

2. Go to [your account settings](https://codepen.io/you/settings/account). There is a button there to pair the accounts. 

3. After the accounts are paired, you'll be able to log in with your GitHub account whenever you like!

Probably best to hit up [private support](http://codepen.io/support) if you continue to have trouble so we can look at your account specifically.
